version: '3.8'
services:
  dbsbrj:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbsbrj
    ports:
      - '5432:5432'
    volumes: 
      - dbsbrj:/var/lib/postgresql/data

  pgadminsbrj:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  dbsbrj:
    driver: local